---
abstract: 'Start async Mojo servers easly'
author:
  - 'Pedro Melo <melo@cpan.org>'
generated_by: 'Dist::Zilla version 1.092800'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Mojo
requires:
  AnyEvent: 5.201
  AnyEvent::HTTP: 1.43
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Carp: 0
  IO::Socket: 0
  Mojo: 0.991251
  Pod::Man: 2.22
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.92
  parent: 0
resources:
  repository: http://github.com/melo/anyevent--mojo/
version: 0.8002
